spring.application.name=gestion-pedidos2
server.port=9292

# Conexión Render
spring.datasource.url=jdbc:postgresql://dpg-d6u83jv5gffc739j39m0-a.oregon-postgres.render.com:5432/apppedidos?sslmode=require
spring.datasource.username=pipeuser
spring.datasource.password=S3oWWWumQvfcCAQse4wVIcmQFRItlg9a
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true