# Configuración de la conexión a Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/db_gestion_pedidos
spring.datasource.username=postgres
spring.datasource.password=Pipemora

# JPA / Hibernate - Esto crea las tablas automáticamente basado en tus Modelos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081